service: sqsService

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'develop'}
  region: ${opt:region, 'us-east-1'}
  timeout: 30
  iamRoleStatements:
  - Effect: Allow
    Action:
      - sqs:GetQueueAttributes
      - sqs:ListQueues
      - sqs:GetQueueUrl
      - sqs:SendMessage
      - sqs:ReceiveMessage
    Resource:
      !GetAtt TrainingQueue.Arn

package:
  exclude:
    - README.md
    - .vscode/*
    - .eslintrc
    - .npmignore
    - node_modules/aws-sdk/**

functions:
  sender:
    handler: src/lambda/producer.handler
    memorySize: 128
    events:
      - http:
          path: api/v1/producer
          method: post
    environment: 
      REGION: ${opt:region, self:provider.region}
      ENDPOINT: https://sqs.${opt:region, self:provider.region}.amazonaws.com/
      SQS_NAME: "${self:service}-TrainingQueue-${self:provider.stage}" 

  consumer:
    handler: src/lambda/consumer.handler
    memorySize: 128
    events:
      - sqs:
          arn: !GetAtt TrainingQueue.Arn
          batchSize: 1

resources:
  Resources:
    TrainingQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "${self:service}-TrainingQueue-${self:provider.stage}"